version: '3'
services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - 27017:27017
    mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      depends_on:
        - mongodb
      ports:
        - 3300:3000
    hl7adtinbound:
      build:
        context: ./inbound_mllp_adt
        dockerfile: Dockerfile
      ports:
        - 1234:1234
      depends_on:
        - mongodb
    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'