version: '3'
services:
    webmonitoring:
      build:
        context: ./monitoring-app
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      depends_on:
        - mongo
      environment:
        - MONGODB_URI=mongodb://mongo:27017/mondatabase
    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - 27017:27017
    mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      depends_on:
        - mongodb
      ports:
        - 3300:3000
    # hl7adtinbound:
    #   build:
    #     context: ./inbound_mllp_adt
    #     dockerfile: Dockerfile
    #   ports:
    #     - 1234:1234
    #   depends_on:
    #     - mongodb
    consumermllpadt:
      build:
        context: ./pattern-flow
        dockerfile: Dockerfile
      ports:
        - 1234:1234
      depends_on:
        - mongodb
        - rabbitmq
    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'